name=input("enter your name":)
surname=input("enter your surname":)
age=input("enter your age":)
num1=input("enter your first number":)
num2=input("enter your second number"":)
print(name)
print(surname)
print(age)
print(num1)
print(num2)
!